export const championDefinitions = {
  aatrox: {
    id: 'Aatrox',
    image: {
      full: 'Aatrox.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 0,
      y: 0,
    },
    key: '266',
    name: 'Aatrox',
  },
  ahri: {
    id: 'Ahri',
    image: {
      full: 'Ahri.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 48,
      y: 0,
    },
    key: '103',
    name: 'Ahri',
  },
  akali: {
    id: 'Akali',
    image: {
      full: 'Akali.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 96,
      y: 0,
    },
    key: '84',
    name: 'Akali',
  },
  akshan: {
    id: 'Akshan',
    image: {
      full: 'Akshan.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 144,
      y: 0,
    },
    key: '166',
    name: 'Akshan',
  },
  alistar: {
    id: 'Alistar',
    image: {
      full: 'Alistar.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 192,
      y: 0,
    },
    key: '12',
    name: 'Alistar',
  },
  amumu: {
    id: 'Amumu',
    image: {
      full: 'Amumu.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 240,
      y: 0,
    },
    key: '32',
    name: 'Amumu',
  },
  anivia: {
    id: 'Anivia',
    image: {
      full: 'Anivia.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 288,
      y: 0,
    },
    key: '34',
    name: 'Anivia',
  },
  annie: {
    id: 'Annie',
    image: {
      full: 'Annie.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 336,
      y: 0,
    },
    key: '1',
    name: 'Annie',
  },
  aphelios: {
    id: 'Aphelios',
    image: {
      full: 'Aphelios.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 384,
      y: 0,
    },
    key: '523',
    name: 'Aphelios',
  },
  ashe: {
    id: 'Ashe',
    image: {
      full: 'Ashe.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 432,
      y: 0,
    },
    key: '22',
    name: 'Ashe',
  },
  aurelionsol: {
    id: 'AurelionSol',
    image: {
      full: 'AurelionSol.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 0,
      y: 48,
    },
    key: '136',
    name: 'Aurelion Sol',
  },
  azir: {
    id: 'Azir',
    image: {
      full: 'Azir.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 48,
      y: 48,
    },
    key: '268',
    name: 'Azir',
  },
  bard: {
    id: 'Bard',
    image: {
      full: 'Bard.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 96,
      y: 48,
    },
    key: '432',
    name: 'Bard',
  },
  blitzcrank: {
    id: 'Blitzcrank',
    image: {
      full: 'Blitzcrank.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 144,
      y: 48,
    },
    key: '53',
    name: 'Blitzcrank',
  },
  brand: {
    id: 'Brand',
    image: {
      full: 'Brand.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 192,
      y: 48,
    },
    key: '63',
    name: 'Brand',
  },
  braum: {
    id: 'Braum',
    image: {
      full: 'Braum.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 240,
      y: 48,
    },
    key: '201',
    name: 'Braum',
  },
  caitlyn: {
    id: 'Caitlyn',
    image: {
      full: 'Caitlyn.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 288,
      y: 48,
    },
    key: '51',
    name: 'Caitlyn',
  },
  camille: {
    id: 'Camille',
    image: {
      full: 'Camille.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 336,
      y: 48,
    },
    key: '164',
    name: 'Camille',
  },
  cassiopeia: {
    id: 'Cassiopeia',
    image: {
      full: 'Cassiopeia.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 384,
      y: 48,
    },
    key: '69',
    name: 'Cassiopeia',
  },
  chogath: {
    id: 'Chogath',
    image: {
      full: 'Chogath.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 432,
      y: 48,
    },
    key: '31',
    name: "Cho'Gath",
  },
  corki: {
    id: 'Corki',
    image: {
      full: 'Corki.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 0,
      y: 96,
    },
    key: '42',
    name: 'Corki',
  },
  darius: {
    id: 'Darius',
    image: {
      full: 'Darius.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 48,
      y: 96,
    },
    key: '122',
    name: 'Darius',
  },
  diana: {
    id: 'Diana',
    image: {
      full: 'Diana.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 96,
      y: 96,
    },
    key: '131',
    name: 'Diana',
  },
  draven: {
    id: 'Draven',
    image: {
      full: 'Draven.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 144,
      y: 96,
    },
    key: '119',
    name: 'Draven',
  },
  drmundo: {
    id: 'DrMundo',
    image: {
      full: 'DrMundo.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 192,
      y: 96,
    },
    key: '36',
    name: 'Dr. Mundo',
  },
  ekko: {
    id: 'Ekko',
    image: {
      full: 'Ekko.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 240,
      y: 96,
    },
    key: '245',
    name: 'Ekko',
  },
  elise: {
    id: 'Elise',
    image: {
      full: 'Elise.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 288,
      y: 96,
    },
    key: '60',
    name: 'Elise',
  },
  evelynn: {
    id: 'Evelynn',
    image: {
      full: 'Evelynn.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 336,
      y: 96,
    },
    key: '28',
    name: 'Evelynn',
  },
  ezreal: {
    id: 'Ezreal',
    image: {
      full: 'Ezreal.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 384,
      y: 96,
    },
    key: '81',
    name: 'Ezreal',
  },
  fiddlesticks: {
    id: 'Fiddlesticks',
    image: {
      full: 'Fiddlesticks.png',
      group: 'champion',
      h: 48,
      sprite: 'champion0.png',
      w: 48,
      x: 432,
      y: 96,
    },
    key: '9',
    name: 'Fiddlesticks',
  },
  fiora: {
    id: 'Fiora',
    image: {
      full: 'Fiora.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 0,
      y: 0,
    },
    key: '114',
    name: 'Fiora',
  },
  fizz: {
    id: 'Fizz',
    image: {
      full: 'Fizz.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 48,
      y: 0,
    },
    key: '105',
    name: 'Fizz',
  },
  galio: {
    id: 'Galio',
    image: {
      full: 'Galio.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 96,
      y: 0,
    },
    key: '3',
    name: 'Galio',
  },
  gangplank: {
    id: 'Gangplank',
    image: {
      full: 'Gangplank.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 144,
      y: 0,
    },
    key: '41',
    name: 'Gangplank',
  },
  garen: {
    id: 'Garen',
    image: {
      full: 'Garen.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 192,
      y: 0,
    },
    key: '86',
    name: 'Garen',
  },
  gnar: {
    id: 'Gnar',
    image: {
      full: 'Gnar.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 240,
      y: 0,
    },
    key: '150',
    name: 'Gnar',
  },
  gragas: {
    id: 'Gragas',
    image: {
      full: 'Gragas.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 288,
      y: 0,
    },
    key: '79',
    name: 'Gragas',
  },
  graves: {
    id: 'Graves',
    image: {
      full: 'Graves.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 336,
      y: 0,
    },
    key: '104',
    name: 'Graves',
  },
  gwen: {
    id: 'Gwen',
    image: {
      full: 'Gwen.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 384,
      y: 0,
    },
    key: '887',
    name: 'Gwen',
  },
  hecarim: {
    id: 'Hecarim',
    image: {
      full: 'Hecarim.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 432,
      y: 0,
    },
    key: '120',
    name: 'Hecarim',
  },
  heimerdinger: {
    id: 'Heimerdinger',
    image: {
      full: 'Heimerdinger.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 0,
      y: 48,
    },
    key: '74',
    name: 'Heimerdinger',
  },
  illaoi: {
    id: 'Illaoi',
    image: {
      full: 'Illaoi.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 48,
      y: 48,
    },
    key: '420',
    name: 'Illaoi',
  },
  irelia: {
    id: 'Irelia',
    image: {
      full: 'Irelia.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 96,
      y: 48,
    },
    key: '39',
    name: 'Irelia',
  },
  ivern: {
    id: 'Ivern',
    image: {
      full: 'Ivern.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 144,
      y: 48,
    },
    key: '427',
    name: 'Ivern',
  },
  janna: {
    id: 'Janna',
    image: {
      full: 'Janna.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 192,
      y: 48,
    },
    key: '40',
    name: 'Janna',
  },
  jarvaniv: {
    id: 'JarvanIV',
    image: {
      full: 'JarvanIV.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 240,
      y: 48,
    },
    key: '59',
    name: 'Jarvan IV',
  },
  jax: {
    id: 'Jax',
    image: {
      full: 'Jax.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 288,
      y: 48,
    },
    key: '24',
    name: 'Jax',
  },
  jayce: {
    id: 'Jayce',
    image: {
      full: 'Jayce.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 336,
      y: 48,
    },
    key: '126',
    name: 'Jayce',
  },
  jhin: {
    id: 'Jhin',
    image: {
      full: 'Jhin.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 384,
      y: 48,
    },
    key: '202',
    name: 'Jhin',
  },
  jinx: {
    id: 'Jinx',
    image: {
      full: 'Jinx.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 432,
      y: 48,
    },
    key: '222',
    name: 'Jinx',
  },
  kaisa: {
    id: 'Kaisa',
    image: {
      full: 'Kaisa.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 0,
      y: 96,
    },
    key: '145',
    name: "Kai'Sa",
  },
  kalista: {
    id: 'Kalista',
    image: {
      full: 'Kalista.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 48,
      y: 96,
    },
    key: '429',
    name: 'Kalista',
  },
  karma: {
    id: 'Karma',
    image: {
      full: 'Karma.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 96,
      y: 96,
    },
    key: '43',
    name: 'Karma',
  },
  karthus: {
    id: 'Karthus',
    image: {
      full: 'Karthus.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 144,
      y: 96,
    },
    key: '30',
    name: 'Karthus',
  },
  kassadin: {
    id: 'Kassadin',
    image: {
      full: 'Kassadin.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 192,
      y: 96,
    },
    key: '38',
    name: 'Kassadin',
  },
  katarina: {
    id: 'Katarina',
    image: {
      full: 'Katarina.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 240,
      y: 96,
    },
    key: '55',
    name: 'Katarina',
  },
  kayle: {
    id: 'Kayle',
    image: {
      full: 'Kayle.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 288,
      y: 96,
    },
    key: '10',
    name: 'Kayle',
  },
  kayn: {
    id: 'Kayn',
    image: {
      full: 'Kayn.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 336,
      y: 96,
    },
    key: '141',
    name: 'Kayn',
  },
  kennen: {
    id: 'Kennen',
    image: {
      full: 'Kennen.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 384,
      y: 96,
    },
    key: '85',
    name: 'Kennen',
  },
  khazix: {
    id: 'Khazix',
    image: {
      full: 'Khazix.png',
      group: 'champion',
      h: 48,
      sprite: 'champion1.png',
      w: 48,
      x: 432,
      y: 96,
    },
    key: '121',
    name: "Kha'Zix",
  },
  kindred: {
    id: 'Kindred',
    image: {
      full: 'Kindred.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 0,
      y: 0,
    },
    key: '203',
    name: 'Kindred',
  },
  kled: {
    id: 'Kled',
    image: {
      full: 'Kled.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 48,
      y: 0,
    },
    key: '240',
    name: 'Kled',
  },
  kogmaw: {
    id: 'KogMaw',
    image: {
      full: 'KogMaw.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 96,
      y: 0,
    },
    key: '96',
    name: "Kog'Maw",
  },
  leblanc: {
    id: 'Leblanc',
    image: {
      full: 'Leblanc.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 144,
      y: 0,
    },
    key: '7',
    name: 'LeBlanc',
  },
  leesin: {
    id: 'LeeSin',
    image: {
      full: 'LeeSin.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 192,
      y: 0,
    },
    key: '64',
    name: 'Lee Sin',
  },
  leona: {
    id: 'Leona',
    image: {
      full: 'Leona.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 240,
      y: 0,
    },
    key: '89',
    name: 'Leona',
  },
  lillia: {
    id: 'Lillia',
    image: {
      full: 'Lillia.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 288,
      y: 0,
    },
    key: '876',
    name: 'Lillia',
  },
  lissandra: {
    id: 'Lissandra',
    image: {
      full: 'Lissandra.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 336,
      y: 0,
    },
    key: '127',
    name: 'Lissandra',
  },
  lucian: {
    id: 'Lucian',
    image: {
      full: 'Lucian.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 384,
      y: 0,
    },
    key: '236',
    name: 'Lucian',
  },
  lulu: {
    id: 'Lulu',
    image: {
      full: 'Lulu.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 432,
      y: 0,
    },
    key: '117',
    name: 'Lulu',
  },
  lux: {
    id: 'Lux',
    image: {
      full: 'Lux.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 0,
      y: 48,
    },
    key: '99',
    name: 'Lux',
  },
  malphite: {
    id: 'Malphite',
    image: {
      full: 'Malphite.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 48,
      y: 48,
    },
    key: '54',
    name: 'Malphite',
  },
  malzahar: {
    id: 'Malzahar',
    image: {
      full: 'Malzahar.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 96,
      y: 48,
    },
    key: '90',
    name: 'Malzahar',
  },
  maokai: {
    id: 'Maokai',
    image: {
      full: 'Maokai.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 144,
      y: 48,
    },
    key: '57',
    name: 'Maokai',
  },
  masteryi: {
    id: 'MasterYi',
    image: {
      full: 'MasterYi.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 192,
      y: 48,
    },
    key: '11',
    name: 'Master Yi',
  },
  missfortune: {
    id: 'MissFortune',
    image: {
      full: 'MissFortune.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 240,
      y: 48,
    },
    key: '21',
    name: 'Miss Fortune',
  },
  monkeyking: {
    id: 'MonkeyKing',
    image: {
      full: 'MonkeyKing.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 288,
      y: 48,
    },
    key: '62',
    name: 'Wukong',
  },
  mordekaiser: {
    id: 'Mordekaiser',
    image: {
      full: 'Mordekaiser.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 336,
      y: 48,
    },
    key: '82',
    name: 'Mordekaiser',
  },
  morgana: {
    id: 'Morgana',
    image: {
      full: 'Morgana.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 384,
      y: 48,
    },
    key: '25',
    name: 'Morgana',
  },
  nami: {
    id: 'Nami',
    image: {
      full: 'Nami.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 432,
      y: 48,
    },
    key: '267',
    name: 'Nami',
  },
  nasus: {
    id: 'Nasus',
    image: {
      full: 'Nasus.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 0,
      y: 96,
    },
    key: '75',
    name: 'Nasus',
  },
  nautilus: {
    id: 'Nautilus',
    image: {
      full: 'Nautilus.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 48,
      y: 96,
    },
    key: '111',
    name: 'Nautilus',
  },
  neeko: {
    id: 'Neeko',
    image: {
      full: 'Neeko.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 96,
      y: 96,
    },
    key: '518',
    name: 'Neeko',
  },
  nidalee: {
    id: 'Nidalee',
    image: {
      full: 'Nidalee.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 144,
      y: 96,
    },
    key: '76',
    name: 'Nidalee',
  },
  nocturne: {
    id: 'Nocturne',
    image: {
      full: 'Nocturne.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 192,
      y: 96,
    },
    key: '56',
    name: 'Nocturne',
  },
  nunu: {
    id: 'Nunu',
    image: {
      full: 'Nunu.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 240,
      y: 96,
    },
    key: '20',
    name: 'Nunu & Willump',
  },
  olaf: {
    id: 'Olaf',
    image: {
      full: 'Olaf.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 288,
      y: 96,
    },
    key: '2',
    name: 'Olaf',
  },
  orianna: {
    id: 'Orianna',
    image: {
      full: 'Orianna.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 336,
      y: 96,
    },
    key: '61',
    name: 'Orianna',
  },
  ornn: {
    id: 'Ornn',
    image: {
      full: 'Ornn.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 384,
      y: 96,
    },
    key: '516',
    name: 'Ornn',
  },
  pantheon: {
    id: 'Pantheon',
    image: {
      full: 'Pantheon.png',
      group: 'champion',
      h: 48,
      sprite: 'champion2.png',
      w: 48,
      x: 432,
      y: 96,
    },
    key: '80',
    name: 'Pantheon',
  },
  poppy: {
    id: 'Poppy',
    image: {
      full: 'Poppy.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 0,
      y: 0,
    },
    key: '78',
    name: 'Poppy',
  },
  pyke: {
    id: 'Pyke',
    image: {
      full: 'Pyke.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 48,
      y: 0,
    },
    key: '555',
    name: 'Pyke',
  },
  qiyana: {
    id: 'Qiyana',
    image: {
      full: 'Qiyana.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 96,
      y: 0,
    },
    key: '246',
    name: 'Qiyana',
  },
  quinn: {
    id: 'Quinn',
    image: {
      full: 'Quinn.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 144,
      y: 0,
    },
    key: '133',
    name: 'Quinn',
  },
  rakan: {
    id: 'Rakan',
    image: {
      full: 'Rakan.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 192,
      y: 0,
    },
    key: '497',
    name: 'Rakan',
  },
  rammus: {
    id: 'Rammus',
    image: {
      full: 'Rammus.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 240,
      y: 0,
    },
    key: '33',
    name: 'Rammus',
  },
  reksai: {
    id: 'RekSai',
    image: {
      full: 'RekSai.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 288,
      y: 0,
    },
    key: '421',
    name: "Rek'Sai",
  },
  rell: {
    id: 'Rell',
    image: {
      full: 'Rell.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 336,
      y: 0,
    },
    key: '526',
    name: 'Rell',
  },
  renekton: {
    id: 'Renekton',
    image: {
      full: 'Renekton.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 384,
      y: 0,
    },
    key: '58',
    name: 'Renekton',
  },
  rengar: {
    id: 'Rengar',
    image: {
      full: 'Rengar.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 432,
      y: 0,
    },
    key: '107',
    name: 'Rengar',
  },
  riven: {
    id: 'Riven',
    image: {
      full: 'Riven.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 0,
      y: 48,
    },
    key: '92',
    name: 'Riven',
  },
  rumble: {
    id: 'Rumble',
    image: {
      full: 'Rumble.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 48,
      y: 48,
    },
    key: '68',
    name: 'Rumble',
  },
  ryze: {
    id: 'Ryze',
    image: {
      full: 'Ryze.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 96,
      y: 48,
    },
    key: '13',
    name: 'Ryze',
  },
  samira: {
    id: 'Samira',
    image: {
      full: 'Samira.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 144,
      y: 48,
    },
    key: '360',
    name: 'Samira',
  },
  sejuani: {
    id: 'Sejuani',
    image: {
      full: 'Sejuani.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 192,
      y: 48,
    },
    key: '113',
    name: 'Sejuani',
  },
  senna: {
    id: 'Senna',
    image: {
      full: 'Senna.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 240,
      y: 48,
    },
    key: '235',
    name: 'Senna',
  },
  seraphine: {
    id: 'Seraphine',
    image: {
      full: 'Seraphine.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 288,
      y: 48,
    },
    key: '147',
    name: 'Seraphine',
  },
  sett: {
    id: 'Sett',
    image: {
      full: 'Sett.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 336,
      y: 48,
    },
    key: '875',
    name: 'Sett',
  },
  shaco: {
    id: 'Shaco',
    image: {
      full: 'Shaco.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 384,
      y: 48,
    },
    key: '35',
    name: 'Shaco',
  },
  shen: {
    id: 'Shen',
    image: {
      full: 'Shen.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 432,
      y: 48,
    },
    key: '98',
    name: 'Shen',
  },
  shyvana: {
    id: 'Shyvana',
    image: {
      full: 'Shyvana.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 0,
      y: 96,
    },
    key: '102',
    name: 'Shyvana',
  },
  singed: {
    id: 'Singed',
    image: {
      full: 'Singed.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 48,
      y: 96,
    },
    key: '27',
    name: 'Singed',
  },
  sion: {
    id: 'Sion',
    image: {
      full: 'Sion.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 96,
      y: 96,
    },
    key: '14',
    name: 'Sion',
  },
  sivir: {
    id: 'Sivir',
    image: {
      full: 'Sivir.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 144,
      y: 96,
    },
    key: '15',
    name: 'Sivir',
  },
  skarner: {
    id: 'Skarner',
    image: {
      full: 'Skarner.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 192,
      y: 96,
    },
    key: '72',
    name: 'Skarner',
  },
  sona: {
    id: 'Sona',
    image: {
      full: 'Sona.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 240,
      y: 96,
    },
    key: '37',
    name: 'Sona',
  },
  soraka: {
    id: 'Soraka',
    image: {
      full: 'Soraka.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 288,
      y: 96,
    },
    key: '16',
    name: 'Soraka',
  },
  swain: {
    id: 'Swain',
    image: {
      full: 'Swain.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 336,
      y: 96,
    },
    key: '50',
    name: 'Swain',
  },
  sylas: {
    id: 'Sylas',
    image: {
      full: 'Sylas.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 384,
      y: 96,
    },
    key: '517',
    name: 'Sylas',
  },
  syndra: {
    id: 'Syndra',
    image: {
      full: 'Syndra.png',
      group: 'champion',
      h: 48,
      sprite: 'champion3.png',
      w: 48,
      x: 432,
      y: 96,
    },
    key: '134',
    name: 'Syndra',
  },
  tahmkench: {
    id: 'TahmKench',
    image: {
      full: 'TahmKench.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 0,
      y: 0,
    },
    key: '223',
    name: 'Tahm Kench',
  },
  taliyah: {
    id: 'Taliyah',
    image: {
      full: 'Taliyah.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 48,
      y: 0,
    },
    key: '163',
    name: 'Taliyah',
  },
  talon: {
    id: 'Talon',
    image: {
      full: 'Talon.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 96,
      y: 0,
    },
    key: '91',
    name: 'Talon',
  },
  taric: {
    id: 'Taric',
    image: {
      full: 'Taric.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 144,
      y: 0,
    },
    key: '44',
    name: 'Taric',
  },
  teemo: {
    id: 'Teemo',
    image: {
      full: 'Teemo.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 192,
      y: 0,
    },
    key: '17',
    name: 'Teemo',
  },
  thresh: {
    id: 'Thresh',
    image: {
      full: 'Thresh.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 240,
      y: 0,
    },
    key: '412',
    name: 'Thresh',
  },
  tristana: {
    id: 'Tristana',
    image: {
      full: 'Tristana.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 288,
      y: 0,
    },
    key: '18',
    name: 'Tristana',
  },
  trundle: {
    id: 'Trundle',
    image: {
      full: 'Trundle.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 336,
      y: 0,
    },
    key: '48',
    name: 'Trundle',
  },
  tryndamere: {
    id: 'Tryndamere',
    image: {
      full: 'Tryndamere.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 384,
      y: 0,
    },
    key: '23',
    name: 'Tryndamere',
  },
  twistedfate: {
    id: 'TwistedFate',
    image: {
      full: 'TwistedFate.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 432,
      y: 0,
    },
    key: '4',
    name: 'Twisted Fate',
  },
  twitch: {
    id: 'Twitch',
    image: {
      full: 'Twitch.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 0,
      y: 48,
    },
    key: '29',
    name: 'Twitch',
  },
  udyr: {
    id: 'Udyr',
    image: {
      full: 'Udyr.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 48,
      y: 48,
    },
    key: '77',
    name: 'Udyr',
  },
  urgot: {
    id: 'Urgot',
    image: {
      full: 'Urgot.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 96,
      y: 48,
    },
    key: '6',
    name: 'Urgot',
  },
  varus: {
    id: 'Varus',
    image: {
      full: 'Varus.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 144,
      y: 48,
    },
    key: '110',
    name: 'Varus',
  },
  vayne: {
    id: 'Vayne',
    image: {
      full: 'Vayne.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 192,
      y: 48,
    },
    key: '67',
    name: 'Vayne',
  },
  veigar: {
    id: 'Veigar',
    image: {
      full: 'Veigar.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 240,
      y: 48,
    },
    key: '45',
    name: 'Veigar',
  },
  velkoz: {
    id: 'Velkoz',
    image: {
      full: 'Velkoz.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 288,
      y: 48,
    },
    key: '161',
    name: "Vel'Koz",
  },
  vex: {
    id: 'Vex',
    image: {
      full: 'Vex.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 336,
      y: 48,
    },
    key: '711',
    name: 'Vex',
  },
  vi: {
    id: 'Vi',
    image: {
      full: 'Vi.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 384,
      y: 48,
    },
    key: '254',
    name: 'Vi',
  },
  viego: {
    id: 'Viego',
    image: {
      full: 'Viego.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 432,
      y: 48,
    },
    key: '234',
    name: 'Viego',
  },
  viktor: {
    id: 'Viktor',
    image: {
      full: 'Viktor.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 0,
      y: 96,
    },
    key: '112',
    name: 'Viktor',
  },
  vladimir: {
    id: 'Vladimir',
    image: {
      full: 'Vladimir.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 48,
      y: 96,
    },
    key: '8',
    name: 'Vladimir',
  },
  volibear: {
    id: 'Volibear',
    image: {
      full: 'Volibear.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 96,
      y: 96,
    },
    key: '106',
    name: 'Volibear',
  },
  warwick: {
    id: 'Warwick',
    image: {
      full: 'Warwick.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 144,
      y: 96,
    },
    key: '19',
    name: 'Warwick',
  },
  xayah: {
    id: 'Xayah',
    image: {
      full: 'Xayah.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 192,
      y: 96,
    },
    key: '498',
    name: 'Xayah',
  },
  xerath: {
    id: 'Xerath',
    image: {
      full: 'Xerath.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 240,
      y: 96,
    },
    key: '101',
    name: 'Xerath',
  },
  xinzhao: {
    id: 'XinZhao',
    image: {
      full: 'XinZhao.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 288,
      y: 96,
    },
    key: '5',
    name: 'Xin Zhao',
  },
  yasuo: {
    id: 'Yasuo',
    image: {
      full: 'Yasuo.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 336,
      y: 96,
    },
    key: '157',
    name: 'Yasuo',
  },
  yone: {
    id: 'Yone',
    image: {
      full: 'Yone.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 384,
      y: 96,
    },
    key: '777',
    name: 'Yone',
  },
  yorick: {
    id: 'Yorick',
    image: {
      full: 'Yorick.png',
      group: 'champion',
      h: 48,
      sprite: 'champion4.png',
      w: 48,
      x: 432,
      y: 96,
    },
    key: '83',
    name: 'Yorick',
  },
  yuumi: {
    id: 'Yuumi',
    image: {
      full: 'Yuumi.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 0,
      y: 0,
    },
    key: '350',
    name: 'Yuumi',
  },
  zac: {
    id: 'Zac',
    image: {
      full: 'Zac.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 48,
      y: 0,
    },
    key: '154',
    name: 'Zac',
  },
  zed: {
    id: 'Zed',
    image: {
      full: 'Zed.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 96,
      y: 0,
    },
    key: '238',
    name: 'Zed',
  },
  ziggs: {
    id: 'Ziggs',
    image: {
      full: 'Ziggs.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 144,
      y: 0,
    },
    key: '115',
    name: 'Ziggs',
  },
  zilean: {
    id: 'Zilean',
    image: {
      full: 'Zilean.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 192,
      y: 0,
    },
    key: '26',
    name: 'Zilean',
  },
  zoe: {
    id: 'Zoe',
    image: {
      full: 'Zoe.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 240,
      y: 0,
    },
    key: '142',
    name: 'Zoe',
  },
  zyra: {
    id: 'Zyra',
    image: {
      full: 'Zyra.png',
      group: 'champion',
      h: 48,
      sprite: 'champion5.png',
      w: 48,
      x: 288,
      y: 0,
    },
    key: '143',
    name: 'Zyra',
  },
}

export type ChampionId = keyof typeof championDefinitions
